
config opennds
	option enabled '1'
	option fwhook_enabled '1'
	option maxclients '250'
	list users_to_router 'allow tcp port 53'
	list users_to_router 'allow udp port 53'
	list users_to_router 'allow udp port 67'
	list users_to_router 'allow tcp port 22'
	list users_to_router 'allow tcp port 80'
	list users_to_router 'allow tcp port 443'
	option login_option_enabled '3'
	option themespec_path '/usr/lib/opennds/mythemespec.sh'
	option binauth '/usr/lib/opennds/binauth_log.sh'
	option preauthidletimeout '5'
	option authidletimeout '60'
